name: Build Counter

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 导入仓库
        uses: actions/checkout@v3
      - name: 加载版本号
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV
      - name: Go环境部署
        uses: actions/setup-go@v3
        with:
          go-version: 1.23.0
      - name: 编译
        run: go build -o counter ./main.go
      - name: 打包
        run: sudo tar -czvf counter.tar.gz ./counter # 将可执行文件打包为 tar.gz
      - name: 上传至Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ./counter*
          tag_name: ${{ env.VERSION }}
          body: "发布版本 ${{ env.VERSION }}"
